initial commit fixed2

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -25,7 +25,7 @@ jobs:
       - name: gradlew bootJar
         run: ./gradlew bootJar
 
-      - name: copy jar to server
+      - name: Copy jar to server
         uses: appleboy/scp-action@master
         with:
           host: ${{ secrets.SSH_HOST }}
@@ -44,6 +44,27 @@ jobs:
           key: ${{ secrets.SSH_KEY }}
           port: 22
           script_stop: true
-          script: /
-            kill -9 $(ps -ef | grep java | head -n 1 | awk '{print $2}')
-            nohup java -jar *.jar 1> /dev/null 2>&1 &
+          script: |
+            # Kill the existing Java process
+            pid=$(pgrep -f 'java -jar')
+            if [ -n "$pid" ]; then
+              kill -9 $pid
+            fi
+            # Verify if the process was killed
+            sleep 2
+            if pgrep -f 'java -jar'; then
+              echo "Failed to kill the existing Java process."
+              exit 1
+            fi
+            # Run the new jar file and log output
+            nohup java -jar *.jar > app.log 2>&1 &
+            # Wait a few seconds to allow the app to start
+            sleep 5
+            # Check if the new process has started
+            if ! pgrep -f 'java -jar'; then
+              echo "Failed to start the Java application."
+              exit 1
+            fi
+            # Display the log file
+            tail -n 100 app.log
+          debug: true
